[package]
name = "manage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
cobul = { git = "https://github.com/tdooms/cobul.git" }
yew-router = "0.16"
api = { path = "../api" }
shared = { path = "../shared" }
strum = "*"
validator = { version = "0.14", features = ["derive"] }