[workspace]
members = ["backend/sessions", "backend/images", "api", "tests",
    "frontend/components", "frontend/create", "frontend/host",
    "frontend/shared", "frontend/manage", "frontend/main", ]