[workspace]
members = ["backend/sessions", "backend/imager", "backend/spar",
    "frontend/agents", "frontend/components", "frontend/create",
    "frontend/host", "frontend/api", "frontend/keys",
    "frontend/main", "frontend/manage", "frontend/shared", "frontend/utils"]