[workspace]
members = ["api", "backend/sessions", "backend/images", "backend/spar",
    "frontend/wasm", "frontend/styles/pbs", "frontend/styles/cbs",
    "frontend/styles/classify", "frontend/styles/fa",
    "tools/fa-scraper"]