[workspace]
resolver = "2"
members = ["backend/sessions", "backend/images", "api", "init",
    "frontend/components", "frontend/create", "frontend/host",
    "frontend/shared", "frontend/manage", "frontend/main"]