[package]
name = "components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }

yew = "0.19"
yew-router = "0.16"

cobul = { git = "https://github.com/tdooms/cobul.git" }