[package]
name = "components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
utils = { path = "../utils" }
agents = { path = "../agents" }
web-sys = { version = "0.3", features = ["HtmlDivElement", "HtmlCanvasElement", "HtmlImageElement"] }
yew = "0.19"
api = { path = "../api" }
yew-router = "0.16"
yew-agent = "0.1"

cobul = { git = "https://github.com/tdooms/cobul.git" }
gloo = "*"
