[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }
#sessions = { path = "../../backend/sessions", features = ["api"], default-features = false }

web-sys = "0.3"
js-sys = "0.3"
yew = "0.19"
