[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }
shared = { path = "../shared" }
cobul = { git = "https://github.com/tdooms/cobul.git" }
components = { path = "../components" }

yew-router = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }
yew = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }

gloo = "0.5"
web-sys = "0.3"
js-sys = "0.3"
qrcode = "0.12"
image = "0.23"
photon-rs = "0.3"
