[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }
shared = { path = "../shared" }
cobul = { git = "https://github.com/tdooms/cobul.git" }
keys = { path = "../keys" }
utils = { path = "../utils" }
components = { path = "../components" }

yew-router = "0.16"
gloo = "*"

web-sys = "0.3"
js-sys = "0.3"
yew = "0.19"
qrcode = "0.12"
image = "0.23"
photon-rs = "0.3"
