[package]
name = "main"
version = "0.1.0"
edition = "2021"
authors = ["thomas <thomas@dooms.eu>"]
description = "a wasm frontend for the pixelguesser game"
repository = "https://github.com/Funkymaniac/pixelguesser"
license = "GNU GPLv3"

[dependencies]
create = { path = "../create" }
host = { path = "../host" }
manage = { path = "../manage" }
api = { path = "../../api", features=["wasm"] }
shared = { path = "../shared" }
components = { path = "../components" }

cobul = { git = "https://github.com/tdooms/cobul.git" }
ywt = { git = "https://github.com/tdooms/ywt.git" }

yew-agent = { git = "https://github.com/yewstack/yew.git", rev = "421b4e1f608e6d648dcf571157b081fcbd886996" }
yew-router = { git = "https://github.com/yewstack/yew.git", rev = "421b4e1f608e6d648dcf571157b081fcbd886996" }
yew = { git = "https://github.com/yewstack/yew.git", rev = "421b4e1f608e6d648dcf571157b081fcbd886996", features = ["csr"] }

strum = { version = "0.24", features = ["derive"] }
derive_more = "*"

serde_json = "1.0"
futures = "0.3"
wasm-logger = "0.2"
wasm-bindgen-futures = "0.4"
log = "0.4"
wee_alloc = "*"

