[package]
name = "main"
version = "0.1.0"
edition = "2021"
authors = ["thomas <thomas@dooms.eu>"]
description = "a wasm frontend for the pixelguesser game"
repository = "https://github.com/Funkymaniac/pixelguesser"
license = "GNU GPLv3"

[dependencies]
create = { path = "../create" }
host = { path = "../host" }
manage = { path = "../manage" }
api = { path = "../api" }
shared = { path = "../shared" }
components = { path = "../components" }
cobul = { git = "https://github.com/tdooms/cobul.git" }

yew-agent = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }
yew-router = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }
yew = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }

futures = "0.3"
wasm-logger = "0.2"
log = "0.4"
wee_alloc = "*"

