[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agents = { path = "../agents" }
create = { path = "../create" }
host = { path = "../host" }
manage = { path = "../manage" }
api = { path = "../api" }
shared = { path = "../shared" }
keys = { path = "../keys" }
utils = { path = "../utils" }
components = { path = "../components" }

futures = "0.3"
wasm-logger = "0.2"
log = "0.4"
wee_alloc = "*"
cobul = { git = "https://github.com/tdooms/cobul.git" }
yew = "0.19"
yew-agent = "0.1"
yew-router = "0.16"
wasm-bindgen = "0.2"