[package]
name = "sessions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4"

warp = "0.3"
tokio = { version = "1.9", features = ["full"] }

serde_json = "1.0.66"

futures = "0.3"
tokio-stream = "0.1"

shared = { path = "../shared" }
clap = "3.0.0-beta.2"
rand = "0.8"