[package]
name = "cbs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbs = { path = "../pbs" }
fa = { path = "../fa" }

yew = { git = "https://github.com/yewstack/yew.git" }

strum = "0.21"
strum_macros = "0.21"
num = "0.4"

derive_more = "0.99.16"