[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }

yew-router = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }
yew = { git = "https://github.com/yewstack/yew.git", rev = "36058d455ce8d068416527836a9aa18afa7b7dee" }

wasm-bindgen = "*"
wasm-bindgen-futures = "*"
serde-wasm-bindgen = "0.4.2"

serde = { version = "*", features = ["derive"] }
gloo = "0.5"
log = "*"
derive_more = "0.99"
futures = "0.3"
thiserror = "1.0"

js-sys = "0.3"
web-sys = { version = "0.3", features = ["CanvasRenderingContext2d"] }

